# Generated by Django 5.2.16 on 2026-07-08 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخطاب')),
                ('content', models.TextField(verbose_name='محتوى الخطاب')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending', 'قيد المراجعة والاعتماد'), ('sent', 'تم الإرسال (صادر)'), ('archived', 'تمت الأرشفة (مغلق)')], default='draft', max_length=20, verbose_name='حالة الخطاب')),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='الرقم المرجعي (الصادر)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('recipient_college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_documents', to='users.college', verbose_name='الكلية المستقبلة')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_documents', to=settings.AUTH_USER_MODEL, verbose_name='المنشئ')),
                ('sender_college', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_documents', to='users.college', verbose_name='الكلية المرسلة')),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', verbose_name='الملف المرفق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='correspondence.document', verbose_name='الخطاب')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء مسودة'), ('request_approval', 'طلب اعتماد دائم'), ('approve_send', 'اعتماد وإرسال'), ('forward', 'توجيه / تحويل داخلي'), ('archive', 'أرشفة وإغلاق المعاملة')], max_length=30, verbose_name='الإجراء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات / توجيهات')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='الوقت والطلب')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='correspondence.document', verbose_name='الخطاب')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن الإجراء')),
            ],
        ),
    ]
