# Generated by Django 5.2.16 on 2026-07-09 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_document_parent'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentForward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات / توجيهات العميد')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='وقت التوجيه')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_forwards', to='users.department', verbose_name='القسم الأكاديمي')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forwards', to='correspondence.document', verbose_name='الخطاب')),
                ('forwarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='الموجّه')),
            ],
        ),
    ]
